services:
  backend:
    build: spring
    ports:
      - "8084:8084"
    networks:
      - calcEv_network

  frontend:
    build: web
    ports:
      - "8085:8085"
    depends_on:
      - backend
    networks:
      - calcEv_network

networks:
  calcEv_network:
    driver: bridge
