services:
  backend:
    build: spring
    ports:
      - "8084:8084"

  frontend:
    build: web
    ports:
      - "8085:8085"
    depends_on:
      - backend
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-enabled/calc.firestorm.team:/etc/nginx/sites-enabled/calc.firestorm.team
      - /etc/letsencrypt:/etc/letsencrypt:ro
