services:
  backend:
    build: spring
    ports:
      - "8084:8084"
    networks:
      - calcev_network

  frontend:
    build: web
    ports:
      - "8085:8085"
      - "443:443"
    depends_on:
      - backend
      - certbot
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/sites-enabled/calc.firestorm.team:/etc/nginx/sites-enabled/calc.firestorm.team:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - calcev_network

networks:
  calcev_network:
    driver: bridge
